# yaml-language-server: $schema=./[current file].yaml
---
# build cluster
# run when cluster_name defined

- name: set cluster name  # noqa 301
  command: "rabbitmqctl set_cluster_name {{ rabbitmq_cluster_name }}"
  changed_when: false

- name: set master to first host in group
  set_fact:
    master: "{{ play_hosts[0] }}"

- name: show master
  debug:
    msg: "master={{ master }}"

- name: check dns configuration  # noqa 301
  command: "grep -q search /etc/resolv.conf"
  ignore_errors: yes
  changed_when: false
  register: search_in_resolvconf

- name: fail if no search domain in resolv.conf
  fail:
    msg: "resolv.conf should contain search domain"
  when: search_in_resolvconf.failed

- name: stop rabbitmq_app
  command: rabbitmqctl stop_app
  when: inventory_hostname != master

- name: reset rabbitmq
  command: rabbitmqctl reset
  when: inventory_hostname != master

- name: join rabbitmq cluster
  command: "rabbitmqctl join_cluster rabbit@{{ hostvars[master]['ansible_hostname'] }}"
  register: cluster_joined
  when: inventory_hostname != master

- name: start rabbitmq
  command: "rabbitmqctl start_app"
  when: inventory_hostname != master

- name: marking as clustered  # noqa 503
  file:
    path: /etc/rabbitmq/clustered
    state: touch
    mode: 0644
    owner: root
    group: root
