---

- name: Configure RabbitMQ
  template:
    dest: '/etc/rabbitmq/rabbitmq.conf'
    group: 'rabbitmq'
    mode: 0644
    owner: 'rabbitmq'
    src: 'rabbitmq.config.j2'
    backup: yes
  notify: Restart RabbitMQ server

- name: Get erlang ssl path
  command: "erl -noinput -eval 'io:format(\"ERL_SSL_PATH=~s~n\", [filename:dirname(code:which(inet_tls_dist))])' -s init stop"
  register: erl_ssl_lib
  when: rabbitmq_ssl_cluster

- name: debug
  debug:
    msg: "erlang ssl lib = {{ erl_ssl_lib.stdout }}"
  when: rabbitmq_ssl_cluster

- name: RabbitMQ Inter-Node TLS config
  template:
    dest: '/etc/rabbitmq/inter_node_tls.config'
    src: 'inter_node_tls.config.j2'
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
    backup: yes
  when: rabbitmq_ssl_cluster

- name: RabbitMQ Environment-specific configuration
  template:
    dest: '/etc/rabbitmq/rabbitmq-env.conf'
    group: 'rabbitmq'
    mode: 0644
    owner: 'rabbitmq'
    src: 'rabbitmq-env.conf.j2'
    backup: yes
  notify: Restart RabbitMQ server

- name: RabbitMQ set Erlang cookie
  template:
    dest: '/var/lib/rabbitmq/.erlang.cookie'
    group: 'rabbitmq'
    owner: 'rabbitmq'
    mode: 0400
    src: 'erlang.cookie.j2'
  notify: Restart RabbitMQ server
  when: rabbitmq_cluster and rabbitmq_erlang_cookie is defined

- name: Set up max file-descriptor limits in RabbitMQ systemd service
  ini_file:
    dest: /etc/systemd/system/rabbitmq-server.service.d/limits.conf
    create: yes
    mode: 0644
    section: Service
    option: LimitNOFILE
    value: '{{ rabbitmq_fd_limit }}'
  notify: Reloaad systemd services and restart RabbitMQ
  when: hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd' and rabbitmq_fd_limit is defined
