---

- name: prefligth | check variables
  fail:
    msg: "rabbitmq_cluster_name variable is required."
  when: rabbitmq_cluster_name is not defined

- name: check dns configuration  # noqa 301
  command: "grep -q search /etc/resolv.conf"
  ignore_errors: yes
  changed_when: false
  register: search_in_resolvconf
  when: >
    rabbitmq_cluster is defined
    and rabbitmq_cluster

- name: fail if no search domain in resolv.conf
  fail:
    msg: "resolv.conf should contain search domain"
  when: >
    search_in_resolvconf.failed
    and rabbitmq_cluster is defined
    and rabbitmq_cluster

- name: preflight | load SSL configuration
  include_vars:
    file: "vars/{{ rabbitmq_cluster_name }}-ssl.yml"
  when: rabbitmq_ssl

- name: preflight | check top level SSL configuration
  fail:
    msg: "certificates required when SSL enabled."
  when: >
    certificates is not defined

- name: preflight | check certificates configuration
  fail:
    msg: "certificates[{{ item }}] required when SSL enabled."
  when: "certificates[ item ] is undefined"
  loop:
    - "ca"
    - "{{ ansible_hostname|lower ~ '.crt' }}"
    - "{{ ansible_hostname|lower ~ '.key' }}"

- name: preflight | load vhosts configuration
  include_vars:
    dir: "vars/vhost/"
    name: vhosts
    extensions:
      - 'yaml'
      - 'yml'

- name: preflight | show vhosts config
  debug:
    msg: " vhost={{ item }}, users = {{ vhosts[item]['rabbitmq_users'] }}, policies={{ vhosts[item]['rabbitmq_policies'] }} "
  with_items: "{{ vhosts }}"
