rabbitmq:
  hosts:
    172.16.128.121:
    172.16.128.122:
    172.16.128.123:
  vars:
    rabbitmq_cluster: true
    rabbitmq_cluster_name: r1
    rabbitmq_ssl: yes
    rabbitmq_ssl_cluster: yes
    rabbitmq_plugins:
      - rabbitmq_management
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_prometheus
      - rabbitmq_shovel
      - rabbitmq_shovel_management

